version: "3.8"

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - microservice-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: sagiri2k4/backend_ktpm:latest
    container_name: backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - microservice-networks

networks:
  microservice-networks:
    driver: bridge
