server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ktpm_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      platform: mysql
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: it3180.devmail@gmail.com
    password: yiuq gvhj bcsg kydv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

jwt:
  signerKey: "In this society, only those who work hard, diligently, and tirelessly will earn their share. Only by working can one eat. Those who expect to eat without working will end up eating sh*t."
  expirationMs: 69696969
